{% set name = "swot_simulator" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CNES/swot_simulator/releases/download/{{ version }}/swot_simulator-{{ version }}.tar.gz
  sha256: cb68507975d69aecb5dff74d9c47601c1e6a2e3495d48676457c2d3ec6b09647

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - swot_simulator = swot_simulator.launcher:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - dask
    - distributed
    - mkl_fft
    - netcdf4
    - numba
    - numpy
    - pyinterp
    - python >={{ python_min }}
    - python-dateutil
    - scipy
    - tornado
    - xarray
test:
  requires:
    - python {{ python_min }}
  imports:
    - swot_simulator.launcher


about:
  home: https://github.com/CNES/swot_simulator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SWOT Simulator for Ocean Science
  description: |
    This software simulates SWOT observations of sea surface height (SSH) that
    can be applied to an ocean general circulation model (OGCM), allowing the
    exploration of ideas and methods to optimize information retrieval from the
    SWOT Mission in the future
  doc_url: https://swot-simulator.readthedocs.io/
  dev_url: https://github.com/CNES/swot_simulator

extra:
  recipe-maintainers:
    - fbriol
    - lgaultier
