{% set name = "swot_simulator" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://github.com/CNES/swot_simulator/releases/download/{{ version }}/swot_simulator-{{ version }}.tar.gz
    sha256: b4d8052a7806baa16da04082c28c5d7c72a0ea16493ec2d07ff9da99469f681e

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - swot_simulator = swot_simulator.launcher:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - dask
    - distributed
    - mkl_fft
    - netcdf4
    - numba
    - numpy
    - pyinterp >=0.3.2
    - python >=3.6
    - python-dateutil
    - scipy
    - xarray
test:
  imports:
    - swot_simulator.launcher


about:
  home: https://github.com/CNES/swot_simulator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'SWOT Simulator for Ocean Science'
  description: |
    This software simulates SWOT observations of sea surface height (SSH) that
    can be applied to an ocean general circulation model (OGCM), allowing the
    exploration of ideas and methods to optimize information retrieval from the
    SWOT Mission in the future
  doc_url: https://swot-simulator.readthedocs.io/
  dev_url: https://github.com/CNES/swot_simulator

extra:
  recipe-maintainers:
    - fbriol
